// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HonorClient is the client API for Honor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HonorClient interface {
	GetHonor(ctx context.Context, in *GetHonorRequest, opts ...grpc.CallOption) (*GetHonorReply, error)
}

type honorClient struct {
	cc grpc.ClientConnInterface
}

func NewHonorClient(cc grpc.ClientConnInterface) HonorClient {
	return &honorClient{cc}
}

func (c *honorClient) GetHonor(ctx context.Context, in *GetHonorRequest, opts ...grpc.CallOption) (*GetHonorReply, error) {
	out := new(GetHonorReply)
	err := c.cc.Invoke(ctx, "/pb.Honor/GetHonor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HonorServer is the server API for Honor service.
// All implementations must embed UnimplementedHonorServer
// for forward compatibility
type HonorServer interface {
	GetHonor(context.Context, *GetHonorRequest) (*GetHonorReply, error)
	mustEmbedUnimplementedHonorServer()
}

// UnimplementedHonorServer must be embedded to have forward compatible implementations.
type UnimplementedHonorServer struct {
}

func (UnimplementedHonorServer) GetHonor(context.Context, *GetHonorRequest) (*GetHonorReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHonor not implemented")
}
func (UnimplementedHonorServer) mustEmbedUnimplementedHonorServer() {}

// UnsafeHonorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HonorServer will
// result in compilation errors.
type UnsafeHonorServer interface {
	mustEmbedUnimplementedHonorServer()
}

func RegisterHonorServer(s grpc.ServiceRegistrar, srv HonorServer) {
	s.RegisterService(&Honor_ServiceDesc, srv)
}

func _Honor_GetHonor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHonorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HonorServer).GetHonor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Honor/GetHonor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HonorServer).GetHonor(ctx, req.(*GetHonorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Honor_ServiceDesc is the grpc.ServiceDesc for Honor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Honor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Honor",
	HandlerType: (*HonorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHonor",
			Handler:    _Honor_GetHonor_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "honor.proto",
}
